#!/bin/bash

#cd /sbox/bpeabody/python/triangleMTB
SCRIPT=`basename "$0"`
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
ZIPDIR=`mktemp -d`
ZIPFILE=$ZIPDIR/file.zip
cd $DIR
zip -r9 $ZIPFILE . -x $SCRIPT -x .\*
aws lambda update-function-code --function-name triangleMTB --zip-file fileb://$ZIPFILE
rm -fr $ZIPDIR
